spring:
  profiles:
    active:  development

---
spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 9000


---
spring:
  profiles: production
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 80