spring:
  profiles:
    active:  development

---
# DEVELOPMENT PROFILE RELATED CONFIGURATION


# H2 Web Console (H2ConsoleProperties)

# -Dspring.profiles.active=test

spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

# ALWAYS, NEVER or DETECT
#FATAL and ERROR – Red
#WARN – Yellow
#INFO, DEBUG and TRACE – Green

    ansi:
        enabled: ALWAYS
# Datasource
  datasource:
    name: sa
    password: studio
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/sims


server:
  port: 9000
logging:
#  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR


---
spring:
  profiles: production
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 80