CREATE TABLE STUDENT(
   ID INT AUTO_INCREMENT,
   NAME VARCHAR(255),
   DEPARTMENT VARCHAR(255),
   MOBILE INT,
   ADDRESS VARCHAR(255)
);

-- CREATE TABLE USER{
--  ID INT ,
--  USER_NAME VARCHAR(255),
--  EMAIL VARCHAR(255),
--  PASSWORD VARCHAR(255),
-- FIRST_NAME VARCHAR(255),
-- LAST_NAME VARCHAR(255),
-- ACTIVE INT NOT NULL,
-- ROLES VARCHAR(255),
-- CREATED_DATE DATE ,
-- UPDATED_DATE DATE
-- };
